"""
08_run_gas3_regime_ndc_feasibility.py  —  GAS-3
================================================

RESEARCH QUESTION (GAS-3)
--------------------------
How does the structural form of gas decline — exponential depletion vs
shock-recovery vs lag-ramp-uplift — affect the cost and feasibility of
NDC compliance independently of the level of gas availability?

ROBUSTNESS GAPS FIXED IN THIS VERSION
--------------------------------------

GAP 1 — CRITICAL: Shape vs Level confound
  The four structural scenarios have different cumulative gas totals:
    baseline:       853.9 TWh_th  (reference)
    downside:       640.4 TWh_th  (-25.0% vs baseline)
    upside:         959.6 TWh_th  (+12.4% vs baseline)
    shock_recovery: 914.0 TWh_th  (+7.0%  vs baseline)

  Any cost/feasibility difference attributed to decline SHAPE could be
  entirely driven by supply LEVEL. The RQ explicitly asks for the shape
  effect INDEPENDENTLY of level.

  Fix: three flat level-equivalent scenarios are added to
  gas_available_power_annual_twh_th.csv by re-running
  build_gas_deliverability.py. They hold cumulative gas identical to
  the paired structural scenario but are constant across the horizon:
    flat_downside:       30.50 TWh_th/yr (= mean of downside)
    flat_upside:         45.69 TWh_th/yr (= mean of upside)
    flat_shock_recovery: 43.52 TWh_th/yr (= mean of shock_recovery)

  Shape effect = cost(structural) - cost(flat_equivalent)
  Positive: structural form is MORE costly than level alone predicts.
  Negative: structural form is CHEAPER (e.g. early solar forced by
            exponential decline hedges against later scarcity).

GAP 2 — IMPORTANT: No annual cap binding diagnostic
  Scalar carbon_shadow_mean cannot distinguish:
    (a) cap binding throughout horizon (downside — progressive tightening)
    (b) cap binding only during disruption years (shock_recovery 2030-2033)
    (c) cap never binding despite abundant gas (upside paradox)
  Fix: annual_ndc_timeseries added to run_gas_regime_ndc_matrix output.
  Expanded here into annual_ndc_binding.csv with cap_binding and
  gas_disrupted flags per year.

GAP 3 — IMPORTANT: Cost premium relative to wrong baseline
  cost(regime) - cost(baseline) conflates level and shape effects.
  True shape_cost_premium = cost(structural) - cost(flat_equivalent).
  Fix: shape_cost_premium.csv computed after both structural and flat
  runs complete.

GAP 4 — MODERATE: Upside paradox not explicitly flagged
  More gas available → model burns more gas → emissions rise → NDC cap
  harder to meet. Test: carbon_shadow_mean(upside) > carbon_shadow_mean(baseline).
  Fix: upside_paradox bool computed and written to gas3_summary.json.

PRE-REQUISITE
-------------
Run build_gas_deliverability.py BEFORE this script to generate
flat_downside, flat_upside, flat_shock_recovery rows in
gas_available_power_annual_twh_th.csv.

OUTPUTS
--------
  results/gas3/regime_ndc_matrix.csv     — structural + flat runs
  results/gas3/regime_feasibility.csv    — feasibility per case
  results/gas3/annual_ndc_binding.csv    — year-by-year cap binding
  results/gas3/shape_cost_premium.csv    — shape effect isolated from level
  results/gas3/gas3_summary.json         — headline findings
"""

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.append(str(ROOT))

from src.io import load_econ
from src.optimize_experiments import run_gas_regime_ndc_matrix

# ============================================================
# CONFIG
# ============================================================

RESULTS_DIR    = ROOT / "results" / "gas3"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

CAP_PATH       = ROOT / "data" / "cost" / "processed" / "emissions_cap.csv"
CANONICAL_VOLL = "voll_mid"

# Four structural shapes — the primary dimension
STRUCTURAL_GAS_CASES = ["baseline", "downside", "upside", "shock_recovery"]

# Level-equivalent flat controls — same cumulative gas, no shape
# Generated by build_gas_deliverability.py (must run first)
FLAT_GAS_CASES = ["flat_downside", "flat_upside", "flat_shock_recovery"]

# Structural → flat pairing for shape isolation
SHAPE_PAIRS = {
    "downside":       "flat_downside",
    "upside":         "flat_upside",
    "shock_recovery": "flat_shock_recovery",
}

# NDC scenarios — unconditional is the primary (tighter cap = harder test)
# Conditional added to check whether a looser cap makes shock feasible
# where unconditional would be infeasible
NDC_SCENARIOS = [
    {"name": "ndc2_unconditional", "capital_case": "moderate"},
    {"name": "ndc2_conditional",   "capital_case": "expansion"},
    {"name": "ndc3_unconditional", "capital_case": "moderate"},
    {"name": "ndc3_conditional",   "capital_case": "expansion"},
]

# Gas anchor (2025 baseline value from gas_deliverability_cases.yaml)
GAS_ANCHOR_TWH_TH = 40.66


# ============================================================
# HELPERS
# ============================================================

def flatten_annual_timeseries(results, ndc_name):
    """
    Expand annual_ndc_timeseries from result dicts into flat rows
    for annual_ndc_binding.csv.

    Adds two derived boolean flags per year-row:
      cap_binding   — True if carbon shadow price > 0 (NDC cap is binding)
      gas_disrupted — True if gas availability < 2025 anchor (40.66 TWh_th)
    """
    rows = []
    for r in results:
        if r.get("status") != "optimal":
            continue
        for yr_row in r.get("annual_ndc_timeseries", []):
            rows.append({
                "gas_case":              r["gas_case"],
                "ndc_scenario":          ndc_name,
                "year":                  yr_row["year"],
                "gas_avail_twh_th":      yr_row["gas_avail_twh_th"],
                "gas_to_power_twh_th":   yr_row["gas_to_power_twh_th"],
                "emissions_tco2":        yr_row["emissions_tco2"],
                "annual_cap_tco2":       yr_row["annual_cap_tco2"],
                "cap_slack_tco2":        yr_row["cap_slack_tco2"],
                "carbon_shadow":         yr_row["carbon_shadow"],
                "unserved_twh":          yr_row["unserved_twh"],
                # Derived flags
                "cap_binding": (
                    yr_row["carbon_shadow"] is not None
                    and yr_row["carbon_shadow"] > 1e-6
                ),
                "gas_disrupted": yr_row["gas_avail_twh_th"] < GAS_ANCHOR_TWH_TH,
                # Key for GAS-3 thesis: does cap bind IN THE SAME YEAR as disruption?
                "cap_and_gas_disruption_coincide": (
                    yr_row["gas_avail_twh_th"] < GAS_ANCHOR_TWH_TH
                    and yr_row["carbon_shadow"] is not None
                    and yr_row["carbon_shadow"] > 1e-6
                ),
            })
    return rows


def compute_shape_premium(structural_results, flat_results, ndc_name):
    """
    For each structural/flat pair compute:
      shape_premium_usd = cost(structural) - cost(flat_equivalent)
      shape_premium_pct = shape_premium_usd / cost(flat_equivalent) * 100

    Positive: the structural form of decline makes NDC compliance more
              costly than the same total supply delivered flat.
    Negative: structural form provides a cost advantage — the shape
              itself is beneficial (e.g. exponential decline forces early
              solar deployment that reduces later gas dependency).
    """
    struct_by = {r["gas_case"]: r for r in structural_results
                 if r.get("status") == "optimal"}
    flat_by   = {r["gas_case"]: r for r in flat_results
                 if r.get("status") == "optimal"}

    rows = []
    for struct_case, flat_case in SHAPE_PAIRS.items():
        r_s = struct_by.get(struct_case)
        r_f = flat_by.get(flat_case)

        base = {
            "gas_case":      struct_case,
            "flat_case":     flat_case,
            "ndc_scenario":  ndc_name,
            "struct_feasible": r_s is not None,
            "flat_feasible":   r_f is not None,
        }

        if r_s is None or r_f is None:
            base.update({
                "struct_cost_usd":   r_s["npv_total_cost_usd"] if r_s else None,
                "flat_cost_usd":     r_f["npv_total_cost_usd"] if r_f else None,
                "shape_premium_usd": None,
                "shape_premium_pct": None,
                "note": "incomplete pair — one or both infeasible",
            })
            rows.append(base)
            continue

        s_cost = r_s["npv_total_cost_usd"]
        f_cost = r_f["npv_total_cost_usd"]
        prem   = s_cost - f_cost
        pct    = prem / f_cost * 100 if f_cost else None

        base.update({
            "struct_cost_usd":              s_cost,
            "flat_cost_usd":                f_cost,
            "shape_premium_usd":            prem,
            "shape_premium_pct":            pct,
            "struct_unserved_twh":          r_s["cumulative_unserved_twh"],
            "flat_unserved_twh":            r_f["cumulative_unserved_twh"],
            "struct_carbon_shadow_mean":    r_s["carbon_shadow_mean"],
            "flat_carbon_shadow_mean":      r_f["carbon_shadow_mean"],
            "struct_carbon_binding_years":  r_s["carbon_binding_years"],
            "flat_carbon_binding_years":    r_f["carbon_binding_years"],
            "interpretation": (
                "Shape makes compliance MORE costly than level alone predicts."
                if prem > 0
                else "Shape makes compliance CHEAPER than level alone "
                     "(structural form provides a cost advantage)."
            ),
        })
        rows.append(base)

    return rows


# ============================================================
# MAIN
# ============================================================

def main():

    econ = load_econ(CANONICAL_VOLL)

    all_structural = []
    all_flat       = []
    all_annual_ts  = []
    all_shape_prem = []

    for ndc_cfg in NDC_SCENARIOS:
        ndc_name = ndc_cfg["name"]

        # ── Structural runs ────────────────────────────────────────────────
        print(f"\n{'='*60}")
        print(f"  GAS-3 STRUCTURAL: {ndc_name}")
        print(f"{'='*60}")

        structural = run_gas_regime_ndc_matrix(
            econ=econ,
            ndc_cap_scenario=ndc_name,
            gas_cases=STRUCTURAL_GAS_CASES,
            financing_regime="traditional",
            capital_case=ndc_cfg["capital_case"],
            cap_path=str(CAP_PATH),
        )
        for r in structural:
            r["ndc_scenario"] = ndc_name
        all_structural.extend(structural)

        for r in structural:
            if r["status"] == "optimal":
                print(
                    f"  {r['gas_case']:<16} "
                    f"cost={r['npv_total_cost_usd']/1e9:.2f}B  "
                    f"unserved={r['cumulative_unserved_twh']:.3f} TWh  "
                    f"carbon_bind={r['carbon_binding_years']}/21  "
                    f"gas_bind={r['gas_shadow_binding_years']}/21"
                )
            else:
                print(f"  {r['gas_case']:<16} [{r['status']}]")

        # ── Annual NDC binding diagnostic ──────────────────────────────────
        ts_rows = flatten_annual_timeseries(structural, ndc_name)
        all_annual_ts.extend(ts_rows)

        # ── Flat level-equivalent runs ─────────────────────────────────────
        print(f"\n  GAS-3 FLAT controls: {ndc_name}")

        flat = run_gas_regime_ndc_matrix(
            econ=econ,
            ndc_cap_scenario=ndc_name,
            gas_cases=FLAT_GAS_CASES,
            financing_regime="traditional",
            capital_case=ndc_cfg["capital_case"],
            cap_path=str(CAP_PATH),
        )
        for r in flat:
            r["ndc_scenario"] = ndc_name
        all_flat.extend(flat)

        for r in flat:
            if r["status"] == "optimal":
                print(
                    f"  {r['gas_case']:<22} "
                    f"cost={r['npv_total_cost_usd']/1e9:.2f}B  "
                    f"carbon_bind={r['carbon_binding_years']}/21"
                )
            else:
                print(f"  {r['gas_case']:<22} [{r['status']}]")

        # ── Shape cost premium ─────────────────────────────────────────────
        prem_rows = compute_shape_premium(structural, flat, ndc_name)
        all_shape_prem.extend(prem_rows)

    # ── Save regime_ndc_matrix.csv ─────────────────────────────────────────
    matrix_rows = []
    for r in all_structural + all_flat:
        matrix_rows.append({
            "gas_case":                  r["gas_case"],
            "ndc_scenario":              r["ndc_scenario"],
            "is_flat_control":           r["gas_case"].startswith("flat_"),
            "status":                    r["status"],
            "npv_total_cost_usd":        r.get("npv_total_cost_usd"),
            "npv_cost_b_usd": (
                r["npv_total_cost_usd"] / 1e9
                if r.get("npv_total_cost_usd") else None
            ),
            "cumulative_unserved_twh":   r.get("cumulative_unserved_twh"),
            "cumulative_emissions_tco2": r.get("cumulative_emissions_tco2"),
            "horizon_reliability":       r.get("horizon_reliability"),
            "gas_shadow_mean":           r.get("gas_shadow_mean"),
            "gas_shadow_binding_years":  r.get("gas_shadow_binding_years"),
            "carbon_shadow_mean":        r.get("carbon_shadow_mean"),
            "carbon_shadow_max":         r.get("carbon_shadow_max"),
            "carbon_binding_years":      r.get("carbon_binding_years"),
            "solar_total_mw":            r.get("solar_total_mw"),
        })

    df_matrix = pd.DataFrame(matrix_rows)
    df_matrix.to_csv(RESULTS_DIR / "regime_ndc_matrix.csv", index=False)

    # ── Save regime_feasibility.csv ────────────────────────────────────────
    feas_rows = [
        {
            "gas_case":      r["gas_case"],
            "ndc_scenario":  r["ndc_scenario"],
            "is_flat":       r["gas_case"].startswith("flat_"),
            "feasible":      r["status"] == "optimal",
            "status":        r["status"],
        }
        for r in all_structural + all_flat
    ]
    pd.DataFrame(feas_rows).to_csv(RESULTS_DIR / "regime_feasibility.csv", index=False)

    # ── Save annual_ndc_binding.csv ────────────────────────────────────────
    pd.DataFrame(all_annual_ts).to_csv(
        RESULTS_DIR / "annual_ndc_binding.csv", index=False
    )

    # ── Save shape_cost_premium.csv ────────────────────────────────────────
    pd.DataFrame(all_shape_prem).to_csv(
        RESULTS_DIR / "shape_cost_premium.csv", index=False
    )

    # ── Build summary JSON ─────────────────────────────────────────────────
    summary = {}

    for ndc_cfg in NDC_SCENARIOS:
        ndc_name = ndc_cfg["name"]

        struct_sub = {
            r["gas_case"]: r for r in all_structural
            if r["ndc_scenario"] == ndc_name and r["status"] == "optimal"
        }
        baseline_cost = struct_sub.get("baseline", {}).get("npv_total_cost_usd")

        # GAP 4: Upside paradox
        upside_c  = struct_sub.get("upside",   {}).get("carbon_shadow_mean", 0.0)
        base_c    = struct_sub.get("baseline", {}).get("carbon_shadow_mean", 0.0)
        upside_paradox = bool(upside_c > base_c)

        # Annual binding coincidence for shock_recovery
        # (does cap bind in the SAME years as gas disruption?)
        ts_shock = [
            row for row in all_annual_ts
            if row["gas_case"] == "shock_recovery"
            and row["ndc_scenario"] == ndc_name
        ]
        coincidence_years = [
            row["year"] for row in ts_shock
            if row["cap_and_gas_disruption_coincide"]
        ]

        # Regime-level detail
        regime_detail = {}
        for gas_case in STRUCTURAL_GAS_CASES:
            r = struct_sub.get(gas_case)
            if r is None:
                regime_detail[gas_case] = {"feasible": False}
                continue

            cost = r["npv_total_cost_usd"]
            level_premium = (
                (cost - baseline_cost) / baseline_cost * 100
                if baseline_cost else None
            )
            shape_p = next(
                (p for p in all_shape_prem
                 if p["gas_case"] == gas_case
                 and p["ndc_scenario"] == ndc_name),
                None
            )

            regime_detail[gas_case] = {
                "feasible":                       True,
                "npv_cost_b_usd":                 cost / 1e9,
                "cost_premium_vs_baseline_pct":   level_premium,
                "shape_cost_premium_pct": (
                    shape_p["shape_premium_pct"] if shape_p else None
                ),
                "shape_cost_premium_usd": (
                    shape_p["shape_premium_usd"] if shape_p else None
                ),
                "carbon_binding_years":           r["carbon_binding_years"],
                "carbon_shadow_mean":             r["carbon_shadow_mean"],
                "gas_shadow_binding_years":       r["gas_shadow_binding_years"],
                "cumulative_unserved_twh":        r["cumulative_unserved_twh"],
            }

        summary[ndc_name] = {
            "upside_paradox_confirmed": upside_paradox,
            "upside_paradox_note": (
                "CONFIRMED: Upside gas worsens NDC compliance — model burns "
                "more gas when supply expands, tightening the emissions cap."
                if upside_paradox
                else "NOT confirmed: Upside gas does not worsen NDC compliance "
                     "at this cap level."
            ),
            "shock_cap_disruption_coincidence_years": coincidence_years,
            "shock_coincidence_note": (
                f"NDC cap binds in the same years as gas disruption "
                f"({len(coincidence_years)} years): {coincidence_years}. "
                "This is the dual-constraint squeeze — less gas AND binding emissions cap."
                if coincidence_years
                else "NDC cap does not bind in years of gas disruption — "
                     "the model substitutes solar without hitting the cap."
            ),
            "regimes": regime_detail,
        }

    with open(RESULTS_DIR / "gas3_summary.json", "w") as f:
        json.dump(summary, f, indent=2)

    # ── Console headline ───────────────────────────────────────────────────
    print(f"\n{'='*80}")
    print("GAS-3 HEADLINE RESULTS")
    print(f"{'='*80}")

    for ndc_name, s in summary.items():
        print(f"\n  NDC: {ndc_name}")
        print(f"  Upside paradox: {s['upside_paradox_confirmed']}  "
              f"— {s['upside_paradox_note'][:65]}")
        print(f"  Shock/cap coincidence years: {s['shock_cap_disruption_coincidence_years']}")
        print()
        print(f"  {'Gas regime':<18} {'Cost(B$)':>9} {'Level Δ%':>9} "
              f"{'Shape Δ%':>9} {'C-bind':>7} {'Unserved':>9}")
        print("  " + "-" * 66)
        for gas_case in STRUCTURAL_GAS_CASES:
            d = s["regimes"].get(gas_case, {})
            if not d.get("feasible"):
                print(f"  {gas_case:<18} INFEASIBLE")
                continue
            c  = f"{d['npv_cost_b_usd']:.2f}"
            lp = (f"{d['cost_premium_vs_baseline_pct']:+.1f}%"
                  if d.get("cost_premium_vs_baseline_pct") is not None else "—")
            sp = (f"{d['shape_cost_premium_pct']:+.1f}%"
                  if d.get("shape_cost_premium_pct") is not None else "n/a")
            cb = f"{d['carbon_binding_years']}/21"
            un = f"{d['cumulative_unserved_twh']:.3f}"
            print(f"  {gas_case:<18} {c:>9} {lp:>9} {sp:>9} {cb:>7} {un:>9}")

    print(f"\nSaved to: {RESULTS_DIR}")
    print()
    print("  regime_ndc_matrix.csv   — structural + flat runs")
    print("  shape_cost_premium.csv  — shape effect isolated from level")
    print("  annual_ndc_binding.csv  — year-by-year cap/disruption interaction")
    print("  regime_feasibility.csv  — feasibility flags")
    print("  gas3_summary.json       — upside paradox, coincidence years, premiums")
    print()
    print("NOTE: flat control scenarios require build_gas_deliverability.py")
    print("      to have been run first (generates flat_* rows in CSV).")


if __name__ == "__main__":
    main()
